### ISSUE TITLE
E Commerce app logo

### ISSUE THREAD

**Issue by mrvozturk** [mrvozturk/DigitalEmporium#18]
digital emporium icin bir logo tasarimi yapilmasi gerekiyor

**Comment by onatvaris** [comment]
[HatchfulExport-All.zip](https://github.com/user-attachments/files/16246955/HatchfulExport-All.zip)

logon uygulama icerisine eklenmesi

**Comment by mrvozturk** [comment]
logo eklendi ve responsive ayarlandı
